const link = [
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5mmdrz3RB1b',
		slidetitle: 'gioithieu',
		displaytext: 'gioithieu',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6AedbN0XtCL',
		slidetitle: 'nd',
		displaytext: 'nd',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6hv0rI1l7VG',
		slidetitle: 'p1',
		displaytext: 'p1',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5VFE1a09Sua',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5bg2spUShEX',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6VXKULQUi5R',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5efMhnS8eyV',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.69oHo7KZOuf',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6m8ur8u4eLR',
		slidetitle: 'hp1',
		displaytext: 'hp1',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5wjqEy1Z88F',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5plV6MxHZMi',
		slidetitle: 'hp2',
		displaytext: 'hp2',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5X8geIrSiFd',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5WwtBvHBorX',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6iaksCKz7jd',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6LdGWzGxcHr',
		slidetitle: 'hp3',
		displaytext: 'hp3',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6f0ij6lgLyt',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5pgTfPk11bB',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6OYmRUfyPUp',
		slidetitle: 'hp4',
		displaytext: 'hp4',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6IXt6o2s9cJ',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6erfoj46cM6',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6q19EcDrQi5',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.6BQmFTjMCbW',
		slidetitle: 'hp5',
		displaytext: 'hp5',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5c30mruT4et',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5jhxv4fiwnA',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
	{
		kind: 'slidelink',
		slideid: '_player.5rye6oJ5hQh.5tZiGslWHhI',
		slidetitle: 'Untitled Slide',
		displaytext: 'Untitled Slide',
		expand: false,
		type: 'slide',
	},
];
